// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5-jBPz0E5C46ky-ydNKTGk37EDrGGeQ',
    appId: '1:175372171586:web:54aaab7fade3ce2559b0db',
    messagingSenderId: '175372171586',
    projectId: 'localnow-ac7cd',
    authDomain: 'localnow-ac7cd.firebaseapp.com',
    storageBucket: 'localnow-ac7cd.appspot.com',
    measurementId: 'G-2Z914EL2KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6BNnqQW5T2nTfTr0DFdU8OflMWhjyCI',
    appId: '1:175372171586:android:8b72d0b0dad9f5cf59b0db',
    messagingSenderId: '175372171586',
    projectId: 'localnow-ac7cd',
    storageBucket: 'localnow-ac7cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6OWnnm1Ip43DHBmz8fykdS5G1mFLQL9U',
    appId: '1:175372171586:ios:b807b176150776ca59b0db',
    messagingSenderId: '175372171586',
    projectId: 'localnow-ac7cd',
    storageBucket: 'localnow-ac7cd.appspot.com',
    iosClientId: '175372171586-gto1tiaqdd2e3lp160flr8oih00k3b8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.localNowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6OWnnm1Ip43DHBmz8fykdS5G1mFLQL9U',
    appId: '1:175372171586:ios:b807b176150776ca59b0db',
    messagingSenderId: '175372171586',
    projectId: 'localnow-ac7cd',
    storageBucket: 'localnow-ac7cd.appspot.com',
    iosClientId: '175372171586-gto1tiaqdd2e3lp160flr8oih00k3b8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.localNowApp',
  );
}
